export default {
  darkMode: 'media',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          tertiary: 'var(--color-bg-tertiary)',
          elevated: 'var(--color-bg-elevated)',
          hover: 'var(--color-bg-hover)',
        },
        surface: {
          primary: 'var(--color-surface-primary)',
          secondary: 'var(--color-surface-secondary)',
          tertiary: 'var(--color-surface-tertiary)',
          hover: 'var(--color-surface-hover)',
          muted: 'var(--color-surface-muted)',
          selected: 'var(--color-surface-selected)',
        },
        accent: {
          primary: 'var(--color-accent-primary)',
          hover: 'var(--color-accent-hover)',
          active: 'var(--color-accent-active)',
          muted: 'var(--color-accent-muted)',
          subtle: 'var(--color-accent-subtle)',
        },
        brand: {
          rosa: '#E83E8C',
          morado: '#9D4EDD',
          turquesa: '#17B3B8',
          amarillo: '#FFC107',
          naranja: '#FF6B35',
        },
        secondary: {
          verde: 'var(--color-secondary-verde)',
          azul: 'var(--color-secondary-azul)',
          rojo: 'var(--color-secondary-rojo)',
          rosa: 'var(--color-secondary-rosa-pastel)',
          aqua: 'var(--color-secondary-aqua)',
        },
        cta: {
          primary: 'var(--color-cta-primary)',
          hover: 'var(--color-cta-hover)',
          active: 'var(--color-cta-active)',
          secondary: 'var(--color-cta-secondary)',
          'secondary-hover': 'var(--color-cta-secondary-hover)',
        },
        interaction: {
          primary: 'var(--color-interaction-primary)',
          hover: 'var(--color-interaction-hover)',
          active: 'var(--color-interaction-active)',
        },
        border: {
          DEFAULT: 'var(--color-border-default)',
          light: 'var(--color-border-light)',
          strong: 'var(--color-border-strong)',
          focus: 'var(--color-border-focus)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          muted: 'var(--color-text-muted)',
          'on-surface': 'var(--color-text-on-surface)',
          'on-accent': 'var(--color-text-on-accent)',
        },
        state: {
          success: 'var(--color-state-success)',
          warning: 'var(--color-state-warning)',
          error: 'var(--color-state-error)',
          info: 'var(--color-state-info)',
          'success-light': 'var(--color-state-success-light)',
          'warning-light': 'var(--color-state-warning-light)',
          'error-light': 'var(--color-state-error-light)',
          'info-light': 'var(--color-state-info-light)',
        },
        overlay: {
          DEFAULT: 'var(--color-overlay)',
          light: 'var(--color-overlay-light)',
        },
        glass: {
          DEFAULT: 'var(--color-glass)',
          border: 'var(--color-glass-border)',
        },
      },
      fontSize: {
        xs: ['11px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        sm: ['13px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        base: ['15px', { lineHeight: '1.5', letterSpacing: '0' }],
        lg: ['17px', { lineHeight: '1.5', letterSpacing: '0' }],
        xl: ['20px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        '2xl': ['24px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        '3xl': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        '4xl': ['34px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        '5xl': ['44px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
      },
      lineHeight: {
        tight: '1.2',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.02em',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
        DEFAULT: '0 1px 3px rgba(0, 0, 0, 0.1)',
        md: '0 4px 6px rgba(0, 0, 0, 0.1)',
        lg: '0 10px 15px rgba(0, 0, 0, 0.1)',
        xl: '0 20px 25px rgba(0, 0, 0, 0.15)',
        '2xl': '0 25px 50px rgba(0, 0, 0, 0.25)',
        card: 'var(--shadow-card)',
        pop: 'var(--shadow-pop)',
        float: 'var(--shadow-float)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}
