const a = (v) => `rgb(var(${v}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // §2.4: el tinte de item seleccionado de modo usa alfa 14 (equivalente exacto
      // a surface-selected oscuro). Escala por defecto de Tailwind no incluye 14.
      opacity: {
        14: '0.14',
      },
      colors: {
        background: {
          primary: a('--color-bg-primary'),
          secondary: a('--color-bg-secondary'),
          tertiary: a('--color-bg-tertiary'),
          elevated: a('--color-bg-elevated'),
        },
        surface: {
          hover: a('--color-surface-hover'),
          sunken: a('--color-surface-sunken'),
          selected: a('--color-surface-selected'),
        },
        accent: {
          DEFAULT: a('--color-accent-primary'),
          primary: a('--color-accent-primary'),
          hover: a('--color-accent-hover'),
          active: a('--color-accent-active'),
          subtle: 'var(--color-accent-subtle)',
          tint: a('--color-accent-tint'),
          text: a('--color-accent-text'),
        },
        mode: {
          chat: a('--color-mode-chat'),
          agent: a('--color-mode-agent'),
          group: a('--color-mode-group'),
        },
        brand: {
          rosa: a('--color-brand-rosa'),
          morado: a('--color-brand-morado'),
          amarillo: a('--color-brand-amarillo'),
          naranja: a('--color-brand-naranja'),
        },
        focus: a('--color-focus'),
        'focus-hover': a('--color-focus-hover'),
        border: {
          DEFAULT: a('--color-border-default'),
          strong: a('--color-border-strong'),
          focus: a('--color-focus'),
        'focus-hover': a('--color-focus-hover'),
        },
        text: {
          primary: a('--color-text-primary'),
          secondary: a('--color-text-secondary'),
          tertiary: a('--color-text-tertiary'),
          muted: a('--color-text-muted'),
          'on-accent': a('--color-text-on-accent'),
        },
        state: {
          success: a('--color-state-success'),
          warning: a('--color-state-warning'),
          error: a('--color-state-error'),
          'error-fill': a('--color-state-error-fill'),
          info: a('--color-state-info'),
        },
        overlay: {
          DEFAULT: 'var(--color-overlay)',
        },
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        xs: ['11px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        sm: ['13px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        base: ['15px', { lineHeight: '1.5', letterSpacing: '0' }],
        lg: ['17px', { lineHeight: '1.5', letterSpacing: '0' }],
        xl: ['20px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        '2xl': ['24px', { lineHeight: '1.375', letterSpacing: '-0.01em' }],
        '3xl': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        '4xl': ['34px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        '5xl': ['44px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
      },
      lineHeight: {
        tight: '1.2',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.02em',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
        DEFAULT: '0 1px 3px rgba(0, 0, 0, 0.1)',
        md: '0 4px 6px rgba(0, 0, 0, 0.1)',
        lg: '0 10px 15px rgba(0, 0, 0, 0.1)',
        xl: '0 20px 25px rgba(0, 0, 0, 0.15)',
        '2xl': '0 25px 50px rgba(0, 0, 0, 0.25)',
        card: 'var(--shadow-card)',
        pop: 'var(--shadow-pop)',
        float: 'var(--shadow-float)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}
